name: gnm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - absl-py
  - etils
  - imageio
  - immutabledict
  - importlib_resources
  - ipywidgets
  - jax
  - jaxtyping
  - mediapy
  - notebook
  - numpy
  - opencv
  - opt-einsum
  - scipy
  - tensorflow
  - tqdm
  - trimesh
  - typeguard
