name: gnm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - absl-py
  - etils
  - imageio
  - immutabledict
  - importlib_resources
  - ipywidgets
  - jax
  - jaxtyping
  - mediapy
  - notebook
  - numpy  
  - opt-einsum
  - scipy
  - tqdm
  - trimesh
  - typeguard
  - rtree
  - pylint
  - pip:
      # Installed via pip to avoid macOS failing to build.
      - opencv-python-headless
      # Installed via pip to avoid macOS dynamic linking conflicts with conda-forge's libprotobuf.
      - tensorflow
      # Not available on conda-forge.
      - tensorflow-graphics
      # Installed via pip to avoid a crash on macOS.
      - torch

